version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.25.3-alpine
    container_name: test_nginx
    ports:
      - 80:80
    volumes:
       - ./:/usr/app/
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build: docker/
    container_name: test_php
    volumes:
      - ./:/usr/app/
